-- taste_blurb_column.sql
-- Run once (idempotent). Adds a cached, AI-written one-line taste "snippet" to
-- each user's Taste Profile (e.g. "Harsh grader with a soft spot for sci-fi").
--
-- The snippet is generated by the taste-profile computer
-- (taste_profile_edge.js, deployed as `swift-responder`) during each recompute —
-- so it costs nothing per page view: the fun Account page just reads this column.
-- Existing rows stay NULL until the user's profile is next recomputed (after a
-- rating save or the daily cron); the front end shows a derived fallback label
-- until then.
--
-- Nothing else changes; re-deploy `swift-responder` after running this.

alter table public."Taste Profiles"
  add column if not exists taste_blurb text;
